package com.selxo.rougo

import android.Manifest
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.media.session.MediaSession
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.util.Size
import android.webkit.JavascriptInterface
import android.webkit.WebView
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.unit.sp
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import androidx.core.content.edit
import java.io.File
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL
import java.util.Locale
import java.util.UUID
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

internal data class YoutubeSubtitleChoice(
    val label: String,
    val languageCode: String,
    val isAutoGenerated: Boolean
)
internal data class YoutubeStreamFormat(
    val formatId: String?,
    val formatNote: String?,
    val ext: String?,
    val vcodec: String?,
    val acodec: String?,
    val height: Int,
    val tbr: Int,
    val url: String?,
    val manifestUrl: String?,
    val protocol: String?,
    val audioUrl: String? = null,
    val audioFormatId: String? = null
)
internal data class YoutubeSetupData(
    val title: String,
    val fallbackUrl: String?,
    val formats: List<YoutubeStreamFormat>,
    val subtitleChoices: List<YoutubeSubtitleChoice>,
    val thumbnailUrl: String? = null,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)
internal data class FastYoutubeStream(
    val title: String,
    val streamUrl: String,
    val formatId: String?,
    val isVideo: Boolean,
    val audioUrl: String? = null,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)
internal data class ResolvedStreamMedia(
    val mediaUrl: String,
    val audioUrl: String? = null
)
private const val DOWNLOAD_NOTIFICATION_PREFS = "rougo_download_notifications"
private const val PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS = "completed_download_notification_ids"
private val completedDownloadNotificationLock = Any()
internal fun isYoutubeUrl(url: String): Boolean {
    val host = runCatching { Uri.parse(url).host.orEmpty().lowercase(Locale.US) }.getOrDefault("")
    return host.contains("youtube.com") || host.contains("youtu.be")
}
internal fun playableYoutubeUrl(url: String): String? {
    return normalizePipePipeStreamUrl(url)?.takeIf { isYoutubeUrl(it) }
}
internal fun youtubeThumbnailUrl(sourceUrl: String?): String? {
    val videoId = youtubeVideoId(sourceUrl) ?: return null
    return "https://i.ytimg.com/vi/$videoId/hqdefault.jpg"
}
private fun youtubeVideoId(sourceUrl: String?): String? {
    val uri = runCatching { Uri.parse(sourceUrl ?: "") }.getOrNull() ?: return null
    val host = uri.host.orEmpty().lowercase(Locale.US)
    val segments = uri.pathSegments
    val candidate = when {
        host == "youtu.be" || host.endsWith(".youtu.be") -> segments.firstOrNull()
        host.contains("youtube.com") -> uri.getQueryParameter("v")
            ?: if (segments.size >= 2 && segments[0] in setOf("shorts", "live", "embed")) segments[1] else null
        else -> null
    }?.trim()

    return candidate?.takeIf { Regex("[A-Za-z0-9_-]{6,}").matches(it) }
}
internal fun isBilibiliUrl(url: String): Boolean {
    val host = runCatching { Uri.parse(url).host.orEmpty().lowercase(Locale.US) }.getOrDefault("")
    return host.contains("bilibili.com") || host == "b23.tv" || host.endsWith(".b23.tv")
}
internal fun isNiconicoUrl(url: String): Boolean {
    val host = runCatching { Uri.parse(url).host.orEmpty().lowercase(Locale.US) }.getOrDefault("")
    return host.contains("nicovideo.jp") || host.contains("nico.ms")
}
internal fun streamSourceLabel(context: Context, url: String?): String {
    if (url.isNullOrBlank()) return context.getString(R.string.media_source_video)
    return when {
        isYoutubeUrl(url) -> context.getString(R.string.media_source_youtube)
        isBilibiliUrl(url) -> context.getString(R.string.media_source_bilibili)
        isNiconicoUrl(url) -> context.getString(R.string.media_source_niconico)
        else -> runCatching { Uri.parse(url).host.orEmpty().removePrefix("www.") }
            .getOrDefault("")
            .ifBlank { context.getString(R.string.media_source_stream) }
    }
}
private fun sourceDefaultTitle(context: Context, url: String): String =
    context.getString(R.string.media_source_default_title, streamSourceLabel(context, url))
private fun cleanImportedTitle(context: Context, value: String?, sourceUrl: String): String? {
    val cleaned = cleanMetadataValue(value)
        ?.replace(Regex("\\s+"), " ")
        ?.takeIf { !looksLikeGeneratedFileId(it) }
    return cleaned ?: sourceDefaultTitle(context, sourceUrl)
}
private fun cleanOptionalImportedTitle(context: Context, value: String?, sourceUrl: String): String? {
    return cleanImportedTitle(context, value, sourceUrl)
        ?.takeIf { it != sourceDefaultTitle(context, sourceUrl) }
}
internal fun looksLikeGeneratedFileId(value: String): Boolean {
    return Regex("(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(?:[._ -].*)?$")
        .matches(value.trim())
}
private fun titleFromDownloadedFile(context: Context, file: File, fileId: String, sourceUrl: String): String? {
    val raw = file.nameWithoutExtension
        .removePrefix(fileId)
        .trimStart('.', '-', '_', ' ')
        .replace(Regex("\\s+"), " ")
    return cleanOptionalImportedTitle(context, raw, sourceUrl)
}
internal fun fetchFastYoutubeStream(context: Context, url: String, preferredResolution: String): FastYoutubeStream? {
    if (!isPipePipeSupportedUrl(url)) return null
    return runCatching { fetchPipePipeFastStream(context, url, preferredResolution) }
        .onFailure { CrashReporter.recordHandled(context, "Fast PipePipe stream", it) }
        .getOrNull()
}
internal fun createFastYoutubeLibraryItem(stream: FastYoutubeStream, sourceUrl: String): LibraryItem {
    return LibraryItem(
        id = UUID.randomUUID().toString(),
        title = stream.title,
        mediaUri = stream.streamUrl,
        subtitleUri = null,
        progress = 0L,
        duration = 0L,
        isVideo = stream.isVideo,
        sourceUrl = sourceUrl,
        formatId = stream.formatId,
        streamAudioUri = stream.audioUrl,
        httpUserAgent = stream.httpUserAgent,
        httpReferer = stream.httpReferer
    )
}
internal class YoutubeBrowserBridge(
    private val onVideoUrl: (String) -> Unit
) {
    private val mainHandler = Handler(Looper.getMainLooper())

    @JavascriptInterface
    fun openVideo(url: String?) {
        val videoUrl = url?.takeIf { it.isNotBlank() } ?: return
        mainHandler.post { onVideoUrl(videoUrl) }
    }
}
internal fun youtubeBrowserInterceptScript(): String {
    return """
        (function() {
            if (window.__rougoYoutubeBridgeInstalled) return;
            window.__rougoYoutubeBridgeInstalled = true;

            function isVideoUrl(rawUrl) {
                try {
                    var url = new URL(rawUrl, window.location.href);
                    var host = url.hostname.toLowerCase();
                    var path = url.pathname || "";
                    return ((host === "youtu.be" || host.endsWith(".youtu.be")) && path.length > 1) ||
                        (host.indexOf("youtube.com") !== -1 &&
                            (url.searchParams.get("v") || /^\/(shorts|live|embed)\//.test(path)));
                } catch (e) {
                    return false;
                }
            }

            function openInRougo(rawUrl) {
                if (!isVideoUrl(rawUrl) || !window.RougoYoutube) return false;
                window.RougoYoutube.openVideo(new URL(rawUrl, window.location.href).href);
                return true;
            }

            document.addEventListener("click", function(event) {
                var node = event.target;
                while (node && node.tagName !== "A") node = node.parentElement;
                if (node && node.href && openInRougo(node.href)) {
                    event.preventDefault();
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                }
            }, true);

            var pushState = history.pushState;
            history.pushState = function() {
                var result = pushState.apply(this, arguments);
                setTimeout(function() { openInRougo(window.location.href); }, 0);
                return result;
            };

            var replaceState = history.replaceState;
            history.replaceState = function() {
                var result = replaceState.apply(this, arguments);
                setTimeout(function() { openInRougo(window.location.href); }, 0);
                return result;
            };

            window.addEventListener("popstate", function() {
                setTimeout(function() { openInRougo(window.location.href); }, 0);
            });

            openInRougo(window.location.href);
        })();
    """.trimIndent()
}
internal fun stopYoutubeWebViewPlayback(webView: WebView?) {
    webView?.stopLoading()
    webView?.evaluateJavascript(
        """
            (function() {
                document.querySelectorAll("video, audio").forEach(function(media) {
                    try {
                        media.pause();
                        media.removeAttribute("src");
                        media.load();
                    } catch (e) {}
                });
            })();
        """.trimIndent(),
        null
    )
}
internal fun fetchYoutubeSetupData(context: Context, url: String): YoutubeSetupData {
    return fetchPipePipeSetupData(context, url)
}
internal suspend fun createYoutubeLibraryItem(
    context: Context,
    setupData: YoutubeSetupData?,
    format: YoutubeStreamFormat,
    subtitleUri: String?,
    sourceUrl: String
): LibraryItem = withContext(Dispatchers.IO) {
    val itemId = UUID.randomUUID().toString()
    val coverArtPath = setupData?.thumbnailUrl?.let { downloadRemoteCover(context, itemId, it) }
    LibraryItem(
        id = itemId,
        title = setupData?.title ?: sourceDefaultTitle(context, sourceUrl),
        mediaUri = sourceUrl,
        subtitleUri = subtitleUri,
        progress = 0L,
        duration = 0L,
        isVideo = format.vcodec != "none",
        sourceUrl = sourceUrl,
        formatId = format.formatId,
        coverArtPath = coverArtPath,
        httpUserAgent = setupData?.httpUserAgent,
        httpReferer = setupData?.httpReferer
    )
}
internal fun downloadRemoteCover(context: Context, itemId: String, url: String): String? {
    return try {
        val connection = URL(url).openConnection() as HttpURLConnection
        connection.connectTimeout = 10000
        connection.readTimeout = 15000
        connection.setRequestProperty("User-Agent", "Mozilla/5.0")
        if (connection.responseCode !in 200..299) return null
        val bytes = connection.inputStream.use { it.readBytes() }
        if (bytes.isEmpty() || bytes.size > 8 * 1024 * 1024) return null
        cacheCoverBytes(context, itemId, bytes)
    } catch (e: Exception) {
        null
    }
}
internal fun youtubeResolutionLabel(context: Context, key: String): String {
    val labelRes = YOUTUBE_RESOLUTION_OPTIONS.firstOrNull { it.key == key }?.labelRes
        ?: R.string.option_youtube_quality_ask
    return context.getString(labelRes)
}
private fun hasPostNotificationsPermission(context: Context): Boolean {
    return Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
        ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED
}
internal fun hasPlayerNotificationPermission(context: Context): Boolean = hasPostNotificationsPermission(context)
private fun createPlayerNotificationChannel(context: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return

    val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (manager.getNotificationChannel(PLAYER_NOTIFICATION_CHANNEL_ID) != null) return

    val channel = NotificationChannel(
        PLAYER_NOTIFICATION_CHANNEL_ID,
        context.getString(R.string.notification_channel_player_name),
        NotificationManager.IMPORTANCE_LOW
    ).apply {
        description = context.getString(R.string.notification_channel_player_description)
        setShowBadge(false)
    }
    manager.createNotificationChannel(channel)
}
private fun createDownloadNotificationChannel(context: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return

    val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (manager.getNotificationChannel(DOWNLOAD_NOTIFICATION_CHANNEL_ID) != null) return

    val channel = NotificationChannel(
        DOWNLOAD_NOTIFICATION_CHANNEL_ID,
        context.getString(R.string.notification_channel_downloads_name),
        NotificationManager.IMPORTANCE_LOW
    ).apply {
        description = context.getString(R.string.notification_channel_downloads_description)
        setShowBadge(false)
    }
    manager.createNotificationChannel(channel)
}
private fun playerNotificationPendingIntent(context: Context, action: String): PendingIntent {
    val flags = PendingIntent.FLAG_UPDATE_CURRENT or
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) PendingIntent.FLAG_IMMUTABLE else 0
    val intent = Intent(action).setPackage(context.packageName)
    return PendingIntent.getBroadcast(context, action.hashCode(), intent, flags)
}
private fun appContentPendingIntent(context: Context, requestCode: Int = 0): PendingIntent {
    val flags = PendingIntent.FLAG_UPDATE_CURRENT or
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) PendingIntent.FLAG_IMMUTABLE else 0
    return PendingIntent.getActivity(
        context,
        requestCode,
        Intent(context, MainActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP),
        flags
    )
}
private fun nativeNotificationBuilder(context: Context, channelId: String): Notification.Builder {
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(context, channelId)
    } else {
        @Suppress("DEPRECATION")
        Notification.Builder(context)
    }
}
private fun nativeNotificationAction(icon: Int, title: String, pendingIntent: PendingIntent): Notification.Action {
    return Notification.Action.Builder(icon, title, pendingIntent).build()
}
internal fun showPlayerNotification(
    context: Context,
    title: String,
    subtitle: String?,
    coverArtPath: String?,
    currentPos: Long,
    duration: Long,
    isPlaying: Boolean,
    skipSeconds: Int,
    mediaSessionToken: MediaSession.Token?
) {
    if (!hasPostNotificationsPermission(context)) return
    createPlayerNotificationChannel(context)

    val timeText = "${formatTime(currentPos)} / ${formatTime(duration)}"
    val largeIcon = coverArtPath?.let { decodeSampledBitmapFile(it, maxSize = 512) }
    val actions = listOf(
        nativeNotificationAction(
            android.R.drawable.ic_media_rew,
            context.getString(R.string.notification_action_rewind, skipSeconds),
            playerNotificationPendingIntent(context, ACTION_PLAYER_REWIND)
        ),
        nativeNotificationAction(
            if (isPlaying) android.R.drawable.ic_media_pause else android.R.drawable.ic_media_play,
            context.getString(if (isPlaying) R.string.common_pause else R.string.common_play),
            playerNotificationPendingIntent(context, ACTION_PLAYER_PLAY_PAUSE)
        ),
        nativeNotificationAction(
            android.R.drawable.ic_media_ff,
            context.getString(R.string.notification_action_forward, skipSeconds),
            playerNotificationPendingIntent(context, ACTION_PLAYER_FORWARD)
        ),
        nativeNotificationAction(
            android.R.drawable.ic_menu_close_clear_cancel,
            context.getString(R.string.common_stop),
            playerNotificationPendingIntent(context, ACTION_PLAYER_STOP)
        )
    )

    val notification = nativeNotificationBuilder(context, PLAYER_NOTIFICATION_CHANNEL_ID)
        .setSmallIcon(if (isPlaying) android.R.drawable.ic_media_play else android.R.drawable.ic_media_pause)
        .setContentTitle(title)
        .setContentText(subtitle ?: timeText)
        .setSubText(timeText)
        .setContentIntent(appContentPendingIntent(context))
        .setDeleteIntent(playerNotificationPendingIntent(context, ACTION_PLAYER_STOP))
        .setVisibility(Notification.VISIBILITY_PUBLIC)
        .setOnlyAlertOnce(true)
        .setShowWhen(false)
        .setOngoing(isPlaying)
        .setCategory(Notification.CATEGORY_TRANSPORT)
        .setPriority(Notification.PRIORITY_LOW)
        .apply {
            if (largeIcon != null) setLargeIcon(largeIcon)
            actions.forEach { addAction(it) }
            setStyle(
                Notification.MediaStyle()
                    .setMediaSession(mediaSessionToken)
                    .setShowActionsInCompactView(0, 1, 2)
            )
        }
        .build()

    try {
        NotificationManagerCompat.from(context).notify(PLAYER_NOTIFICATION_ID, notification)
    } catch (e: SecurityException) {
        e.printStackTrace()
    }
}
internal fun cancelPlayerNotification(context: Context) {
    try {
        NotificationManagerCompat.from(context).cancel(PLAYER_NOTIFICATION_ID)
    } catch (e: Exception) {
        e.printStackTrace()
    }
}
private fun downloadNotificationId(key: String): Int {
    return DOWNLOAD_NOTIFICATION_ID_BASE + ((key.hashCode() and 0x7fffffff) % 1000)
}
private fun completedDownloadPrefs(context: Context) =
    context.applicationContext.getSharedPreferences(DOWNLOAD_NOTIFICATION_PREFS, Context.MODE_PRIVATE)

private fun rememberCompletedDownloadNotification(context: Context, notificationId: Int) {
    synchronized(completedDownloadNotificationLock) {
        val prefs = completedDownloadPrefs(context)
        val current = prefs.getStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, emptySet()).orEmpty()
        prefs.edit {
            putStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, current + notificationId.toString())
        }
    }
}

private fun forgetCompletedDownloadNotification(context: Context, notificationId: Int) {
    synchronized(completedDownloadNotificationLock) {
        val prefs = completedDownloadPrefs(context)
        val current = prefs.getStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, emptySet()).orEmpty()
        if (current.isNotEmpty()) {
            prefs.edit {
                putStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, current - notificationId.toString())
            }
        }
    }
}

internal fun clearCompletedDownloadNotifications(context: Context) {
    val ids = synchronized(completedDownloadNotificationLock) {
        val prefs = completedDownloadPrefs(context)
        val current = prefs.getStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, emptySet()).orEmpty()
        prefs.edit { remove(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS) }
        current.mapNotNull { it.toIntOrNull() }
    }
    ids.forEach { notificationId ->
        try {
            NotificationManagerCompat.from(context).cancel(notificationId)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}

private fun cancelDownloadNotification(context: Context, key: String) {
    val notificationId = downloadNotificationId(key)
    forgetCompletedDownloadNotification(context, notificationId)
    try {
        NotificationManagerCompat.from(context).cancel(notificationId)
    } catch (e: Exception) {
        e.printStackTrace()
    }
}

private fun showDownloadNotification(context: Context, key: String, notification: NotificationCompat.Builder.() -> Unit): Boolean {
    if (!hasPostNotificationsPermission(context)) return false
    createDownloadNotificationChannel(context)

    val builder = NotificationCompat.Builder(context, DOWNLOAD_NOTIFICATION_CHANNEL_ID)
        .setSmallIcon(android.R.drawable.stat_sys_download)
        .setContentIntent(appContentPendingIntent(context, downloadNotificationId(key)))
        .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
        .setOnlyAlertOnce(true)
        .setShowWhen(true)
        .setLocalOnly(false)
        .apply(notification)

    try {
        NotificationManagerCompat.from(context).notify(downloadNotificationId(key), builder.build())
        return true
    } catch (e: SecurityException) {
        e.printStackTrace()
        return false
    }
}
private fun showDownloadProgressNotification(
    context: Context,
    key: String,
    title: String,
    progressPercent: Int?,
    detail: String = context.getString(R.string.download_progress_downloading)
) {
    forgetCompletedDownloadNotification(context, downloadNotificationId(key))
    showDownloadNotification(context, key) {
        setSmallIcon(android.R.drawable.stat_sys_download)
        setContentTitle(title)
        setContentText(detail)
        setOngoing(true)
        setAutoCancel(false)
        setCategory(NotificationCompat.CATEGORY_PROGRESS)
        setPriority(NotificationCompat.PRIORITY_LOW)
        if (progressPercent != null) {
            setProgress(100, progressPercent.coerceIn(0, 100), false)
        } else {
            setProgress(0, 0, true)
        }
    }
}
private fun showDownloadCompleteNotification(context: Context, key: String, title: String) {
    if (RougoForegroundTracker.isForeground) {
        cancelDownloadNotification(context, key)
        return
    }

    val posted = showDownloadNotification(context, key) {
        setSmallIcon(android.R.drawable.stat_sys_download_done)
        setContentTitle(context.getString(R.string.download_complete_title))
        setContentText(title)
        setOngoing(false)
        setAutoCancel(true)
        setCategory(NotificationCompat.CATEGORY_STATUS)
        setPriority(NotificationCompat.PRIORITY_DEFAULT)
        setProgress(0, 0, false)
    }
    if (posted) rememberCompletedDownloadNotification(context, downloadNotificationId(key))
}
private fun showDownloadFailedNotification(context: Context, key: String, title: String, cancelled: Boolean = false) {
    forgetCompletedDownloadNotification(context, downloadNotificationId(key))
    showDownloadNotification(context, key) {
        setSmallIcon(android.R.drawable.stat_notify_error)
        setContentTitle(context.getString(if (cancelled) R.string.download_cancelled_title else R.string.download_failed_title))
        setContentText(title)
        setOngoing(false)
        setAutoCancel(true)
        setCategory(NotificationCompat.CATEGORY_ERROR)
        setPriority(NotificationCompat.PRIORITY_DEFAULT)
        setProgress(0, 0, false)
    }
}
private fun downloadProgressDetail(context: Context, progressPercent: Int?): String {
    if (progressPercent == null) {
        return context.getString(R.string.download_progress_downloading)
    }
    return context.getString(R.string.download_progress_percent_only, progressPercent)
}
internal fun selectPreferredYoutubeSubtitle(choices: List<YoutubeSubtitleChoice>, preferredLanguage: String): YoutubeSubtitleChoice? {
    if (choices.isEmpty()) return null
    if (preferredLanguage == "any") return choices.firstOrNull()

    val normalized = preferredLanguage.lowercase(Locale.US)
    return choices.firstOrNull { choice ->
        val code = choice.languageCode.lowercase(Locale.US)
        code == normalized || code.startsWith("$normalized-")
    } ?: choices.firstOrNull()
}
private fun youtubeSubtitleChoiceKey(choice: YoutubeSubtitleChoice): String {
    return "${choice.languageCode}:${choice.isAutoGenerated}"
}
private fun preferredYoutubeSubtitleCandidates(
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): List<YoutubeSubtitleChoice> {
    val preferredChoice = selectPreferredYoutubeSubtitle(choices, preferredLanguage) ?: return emptyList()
    val normalizedPreference = preferredLanguage.lowercase(Locale.US)
    val preferredLanguageMatches = if (normalizedPreference == "any") {
        emptyList()
    } else {
        choices.filter { choice ->
            val code = choice.languageCode.lowercase(Locale.US)
            code == normalizedPreference || code.startsWith("$normalizedPreference-")
        }
    }
    return (listOf(preferredChoice) +
        choices.filter { it.languageCode == preferredChoice.languageCode } +
        preferredLanguageMatches +
        choices.take(2))
        .distinctBy { youtubeSubtitleChoiceKey(it) }
}
internal fun downloadPreferredYoutubeSubtitle(
    context: Context,
    url: String,
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): String? {
    preferredYoutubeSubtitleCandidates(choices, preferredLanguage).forEach { choice ->
        val subtitleUri = downloadYoutubeSubtitle(context, url, choice.languageCode, choice.isAutoGenerated)
        if (subtitleUri != null) return subtitleUri
    }
    return null
}
internal fun selectPreferredYoutubeFormat(
    formats: List<YoutubeStreamFormat>,
    preferredResolution: String
): YoutubeStreamFormat? {
    val playable = formats.filter { !it.url.isNullOrBlank() || !it.manifestUrl.isNullOrBlank() }
    val audioFormats = playable
        .filter { it.vcodec == "none" && it.acodec != "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { if (it.isVlcFriendlyAudioFormat()) 1 else 0 }.thenByDescending { it.tbr }.thenByDescending { it.formatId ?: "" })
    val videoFormats = playable
        .filter { it.vcodec != "none" && it.acodec != "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { it.height }.thenByDescending { if (it.isVlcFriendlyVideoFormat()) 1 else 0 }.thenByDescending { it.tbr })
    val videoOnlyFormats = playable
        .filter { it.vcodec != "none" && it.acodec == "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { it.height }.thenByDescending { it.tbr })

    return when (preferredResolution) {
        YOUTUBE_RESOLUTION_AUDIO -> audioFormats.firstOrNull() ?: videoFormats.firstOrNull() ?: videoOnlyFormats.firstOrNull()
        YOUTUBE_RESOLUTION_HIGHEST -> videoFormats.firstOrNull() ?: videoOnlyFormats.firstOrNull() ?: audioFormats.firstOrNull()
        else -> {
            val targetHeight = preferredResolution.toIntOrNull()
            if (targetHeight == null) {
                videoFormats.firstOrNull() ?: videoOnlyFormats.firstOrNull() ?: audioFormats.firstOrNull()
            } else {
                videoFormats.firstOrNull { it.height in 1..targetHeight }
                    ?: videoFormats.lastOrNull()
                    ?: videoOnlyFormats.firstOrNull { it.height in 1..targetHeight }
                    ?: videoOnlyFormats.lastOrNull()
                    ?: audioFormats.firstOrNull()
            }
        }
    }
}
internal fun resolveYoutubeStreamUrl(context: Context, url: String, formatId: String?): String? {
    return resolveYoutubeStreamMedia(context, url, formatId)?.mediaUrl
}
internal fun resolveYoutubeStreamMedia(context: Context, url: String, formatId: String?): ResolvedStreamMedia? {
    return resolvePipePipeStreamMedia(context, url, formatId)
}
internal fun downloadYoutubeSubtitle(context: Context, url: String, languageCode: String, isAutoGenerated: Boolean): String? {
    if (!isPipePipeSupportedUrl(url)) return null
    return downloadPipePipeSubtitle(context, url, languageCode, isAutoGenerated)
        ?: if (!isAutoGenerated) downloadPipePipeSubtitle(context, url, languageCode, true) else null
}
private data class MediaDownloadSelection(
    val setupData: YoutubeSetupData,
    val format: YoutubeStreamFormat,
    val mediaUrl: String,
    val audioUrl: String?,
    val outputExtension: String,
    val requiresFfmpeg: Boolean
)

private fun selectMediaDownload(context: Context, url: String): MediaDownloadSelection? {
    if (!isPipePipeSupportedUrl(url)) return null
    val setupData = fetchYoutubeSetupData(context, url)
    val selected = selectPreferredYoutubeFormat(setupData.formats, DEFAULT_YOUTUBE_RESOLUTION)
        ?: setupData.formats.firstOrNull { it.playbackUrl() != null }
        ?: return null
    val mediaUrl = selected.playbackUrl() ?: setupData.fallbackUrl ?: return null
    return MediaDownloadSelection(
        setupData = setupData,
        format = selected,
        mediaUrl = mediaUrl,
        audioUrl = selected.audioUrl?.takeIf { it.isNotBlank() },
        outputExtension = selected.downloadOutputExtension(),
        requiresFfmpeg = !selected.isDirectHttpDownload() || !selected.audioUrl.isNullOrBlank()
    )
}

private fun YoutubeStreamFormat.isDirectHttpDownload(): Boolean {
    val directUrl = url?.takeIf { it.isNotBlank() } ?: return false
    val protocolValue = protocol?.lowercase(Locale.US).orEmpty()
    val extValue = ext?.lowercase(Locale.US).orEmpty()
    return directUrl.startsWith("http", ignoreCase = true) &&
        !protocolValue.contains("hls") &&
        !protocolValue.contains("dash") &&
        !protocolValue.contains("m3u8") &&
        extValue != "m3u8" &&
        extValue != "mpd"
}

private fun YoutubeStreamFormat.downloadOutputExtension(): String {
    val extValue = ext?.lowercase(Locale.US)?.takeIf { it.matches(Regex("[a-z0-9]{2,5}")) }
    if (extValue != null && extValue !in setOf("m3u8", "mpd")) return extValue
    return if (vcodec == "none") "m4a" else "mp4"
}

private fun safeDownloadFileComponent(value: String): String {
    return cleanMetadataValue(value)
        ?.replace(Regex("[\\\\/:*?\"<>|]"), "_")
        ?.replace(Regex("\\s+"), " ")
        ?.trim('.', ' ')
        ?.take(80)
        ?.takeIf { it.isNotBlank() }
        ?: "download"
}

private fun downloadExtractedStreamDirectly(
    context: Context,
    selection: MediaDownloadSelection,
    outputFile: File,
    onProgress: (Int?) -> Unit
): Boolean {
    val connection = (URL(selection.mediaUrl).openConnection() as HttpURLConnection).apply {
        connectTimeout = 15000
        readTimeout = 30000
        instanceFollowRedirects = true
        setRequestProperty("User-Agent", selection.setupData.httpUserAgent ?: "Mozilla/5.0")
        selection.setupData.httpReferer?.takeIf { it.isNotBlank() }?.let { setRequestProperty("Referer", it) }
    }

    return try {
        val responseCode = connection.responseCode
        if (responseCode !in 200..299) throw IOException("Download request failed: HTTP $responseCode")

        val totalBytes = connection.contentLengthLong.takeIf { it > 0L }
        var downloadedBytes = 0L
        var lastProgressPercent = -1
        var lastProgressNotificationAt = 0L

        connection.inputStream.use { input ->
            outputFile.outputStream().use { output ->
                val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                while (true) {
                    val read = input.read(buffer)
                    if (read < 0) break
                    output.write(buffer, 0, read)
                    downloadedBytes += read

                    val progressPercent = totalBytes
                        ?.let { ((downloadedBytes * 100L) / it).toInt().coerceIn(0, 100) }
                    val now = System.currentTimeMillis()
                    val progressChanged = progressPercent != null && progressPercent != lastProgressPercent
                    if (progressChanged || now - lastProgressNotificationAt >= 1000L) {
                        lastProgressNotificationAt = now
                        if (progressPercent != null) lastProgressPercent = progressPercent
                        onProgress(progressPercent)
                    }
                }
            }
        }

        outputFile.length() > 0L
    } finally {
        connection.disconnect()
    }
}

private fun downloadExtractedStreamWithFfmpeg(
    context: Context,
    selection: MediaDownloadSelection,
    outputFile: File
): Boolean {
    val cmd = mutableListOf("-y", "-hide_banner", "-loglevel", "error", "-nostdin")
    fun addInputHeaders() {
        selection.setupData.httpUserAgent?.takeIf { it.isNotBlank() }?.let {
            cmd.add("-user_agent")
            cmd.add(it)
        }
        selection.setupData.httpReferer?.takeIf { it.isNotBlank() }?.let {
            cmd.add("-headers")
            cmd.add("Referer: $it\r\n")
        }
    }
    addInputHeaders()
    cmd.add("-i")
    cmd.add(selection.mediaUrl)
    if (!selection.audioUrl.isNullOrBlank()) {
        addInputHeaders()
        cmd.add("-i")
        cmd.add(selection.audioUrl)
        cmd.add("-map")
        cmd.add("0:v:0")
        cmd.add("-map")
        cmd.add("1:a:0")
        cmd.add("-shortest")
    }
    if (selection.outputExtension == "mp4") {
        cmd.add("-c")
        cmd.add("copy")
        cmd.add("-movflags")
        cmd.add("+faststart")
    } else {
        cmd.add("-c")
        cmd.add("copy")
    }
    cmd.add(outputFile.absolutePath)

    return executeFfmpeg(context, cmd.toTypedArray()) == 0 && outputFile.length() > 0L
}

internal fun downloadVideoLinkToLibraryItem(context: Context, url: String, existingItem: LibraryItem? = null): LibraryItem? {
    val itemId = existingItem?.id ?: UUID.randomUUID().toString()
    val fileId = itemId.replace(Regex("[^A-Za-z0-9_-]"), "_")
    val notificationKey = "media_download_$fileId"
    val initialTitle = existingItem?.title?.takeIf { !looksLikeGeneratedFileId(it) }
        ?: sourceDefaultTitle(context, url)

    showDownloadProgressNotification(context, notificationKey, initialTitle, null, context.getString(R.string.download_progress_preparing))

    val selection = runCatching { selectMediaDownload(context, url) }
        .onFailure { CrashReporter.recordHandled(context, "Prepare PipePipe download", it) }
        .getOrNull()
    if (selection == null) {
        showDownloadFailedNotification(context, notificationKey, initialTitle)
        return null
    }

    val setupData = selection.setupData
    val notificationTitle = cleanOptionalImportedTitle(context, setupData.title, url) ?: initialTitle
    val destDir = File(context.getExternalFilesDir(Environment.DIRECTORY_MOVIES), "RougoDownloads").apply { mkdirs() }
    val safeTitle = safeDownloadFileComponent(notificationTitle)
    val tempFile = File(destDir, "$fileId.$safeTitle.${selection.outputExtension}.download")
    val downloadedFile = File(destDir, "$fileId.$safeTitle.${selection.outputExtension}")

    return try {
        showDownloadProgressNotification(context, notificationKey, notificationTitle, null, context.getString(R.string.download_progress_starting))

        try { tempFile.delete() } catch (e: Exception) {}
        try { downloadedFile.delete() } catch (e: Exception) {}

        val downloadSucceeded = if (selection.requiresFfmpeg) {
            downloadExtractedStreamWithFfmpeg(
                context = context,
                selection = selection,
                outputFile = tempFile
            )
        } else {
            downloadExtractedStreamDirectly(
                context = context,
                selection = selection,
                outputFile = tempFile,
                onProgress = { progressPercent ->
                    showDownloadProgressNotification(
                        context = context,
                        key = notificationKey,
                        title = notificationTitle,
                        progressPercent = progressPercent,
                        detail = downloadProgressDetail(context, progressPercent)
                    )
                }
            )
        }

        if (!downloadSucceeded || tempFile.length() <= 0L) {
            showDownloadFailedNotification(context, notificationKey, notificationTitle)
            try { tempFile.delete() } catch (e: Exception) {}
            return null
        }

        if (!tempFile.renameTo(downloadedFile)) {
            tempFile.copyTo(downloadedFile, overwrite = true)
            try { tempFile.delete() } catch (e: Exception) {}
        }

        showDownloadProgressNotification(context, notificationKey, notificationTitle, 100, context.getString(R.string.download_progress_finalizing))
        if (!downloadedFile.exists() || downloadedFile.length() <= 0L) {
            showDownloadFailedNotification(context, notificationKey, notificationTitle)
            return null
        }

        val mediaUri = Uri.fromFile(downloadedFile)
        val isVideo = selection.format.vcodec != "none"
        val metadata = extractMediaMetadata(context, mediaUri, itemId, isVideo = isVideo)
        val fallbackTitle = cleanOptionalImportedTitle(context, setupData.title, url)
            ?: existingItem?.title?.takeIf { !looksLikeGeneratedFileId(it) }
            ?: titleFromDownloadedFile(context, downloadedFile, fileId, url)
            ?: sourceDefaultTitle(context, url)
        val baseItem = LibraryItem(
            id = itemId,
            title = fallbackTitle,
            mediaUri = mediaUri.toString(),
            subtitleUri = existingItem?.subtitleUri,
            progress = existingItem?.progress ?: 0L,
            duration = metadata.durationMs ?: 0L,
            isVideo = isVideo,
            sourceUrl = existingItem?.sourceUrl ?: url,
            formatId = selection.format.formatId ?: existingItem?.formatId,
            recordings = existingItem?.recordings ?: emptyList(),
            coverArtPath = metadata.coverArtPath
                ?: setupData.thumbnailUrl?.let { downloadRemoteCover(context, itemId, it) }
                ?: existingItem?.coverArtPath,
            httpUserAgent = existingItem?.httpUserAgent ?: setupData.httpUserAgent,
            httpReferer = existingItem?.httpReferer ?: setupData.httpReferer
        )
        val mergedItem = mergeMetadataIntoItem(baseItem, metadata, fallbackTitle)
        showDownloadCompleteNotification(context, notificationKey, mergedItem.title)
        mergedItem
    } catch (t: Throwable) {
        t.printStackTrace()
        CrashReporter.recordHandled(context, "Download video link", t)
        showDownloadFailedNotification(
            context,
            notificationKey,
            notificationTitle,
            cancelled = t is InterruptedException || t::class.java.simpleName.contains("Canceled", ignoreCase = true)
        )
        null
    } finally {
        if (tempFile.exists()) {
            try { tempFile.delete() } catch (e: Exception) {}
        }
    }
}
internal fun initialPlayableMediaUri(item: LibraryItem): String? {
    val mediaUri = item.mediaUri.trim()
    if (mediaUri.isBlank()) return null
    if (item.sourceUrl == null) return mediaUri
    if (item.hasDownloadedLocalCopy()) return mediaUri
    if (mediaUri != item.sourceUrl.trim()) return mediaUri
    return null
}
internal fun YoutubeStreamFormat.isVlcFriendlyVideoFormat(): Boolean {
    if (vcodec == "none" || acodec == "none") return false
    val extValue = ext?.lowercase(Locale.US).orEmpty()
    val videoCodec = vcodec?.lowercase(Locale.US).orEmpty()
    val audioCodec = acodec?.lowercase(Locale.US).orEmpty()
    return extValue == "mp4" &&
        (videoCodec.startsWith("avc") || videoCodec.startsWith("h264")) &&
        (audioCodec.startsWith("mp4a") || audioCodec.startsWith("aac"))
}
internal fun YoutubeStreamFormat.isVlcFriendlyAudioFormat(): Boolean {
    if (vcodec != "none" || acodec == "none") return false
    val extValue = ext?.lowercase(Locale.US).orEmpty()
    val audioCodec = acodec?.lowercase(Locale.US).orEmpty()
    return extValue == "m4a" || extValue == "mp4" || audioCodec.startsWith("mp4a") || audioCodec.startsWith("aac")
}
