package com.selxo.rougo

import android.Manifest
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.media.session.MediaSession
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.os.Handler
import android.os.Looper
import android.os.SystemClock
import android.util.Log
import android.util.Size
import android.webkit.JavascriptInterface
import android.webkit.WebView
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.unit.sp
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import androidx.core.content.edit
import com.yausername.ffmpeg.FFmpeg
import com.yausername.ffmpeg.execute
import com.yausername.youtubedl_android.YoutubeDL
import com.yausername.youtubedl_android.YoutubeDLRequest
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.util.Locale
import java.util.UUID
import kotlin.math.roundToInt
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject

internal data class YoutubeSubtitleChoice(
    val label: String,
    val languageCode: String,
    val isAutoGenerated: Boolean
)
internal data class YoutubeStreamFormat(
    val formatId: String?,
    val formatNote: String?,
    val ext: String?,
    val vcodec: String?,
    val acodec: String?,
    val height: Int,
    val tbr: Int,
    val url: String?,
    val manifestUrl: String?,
    val protocol: String?
)
internal data class YoutubeSetupData(
    val title: String,
    val fallbackUrl: String?,
    val formats: List<YoutubeStreamFormat>,
    val subtitleChoices: List<YoutubeSubtitleChoice>,
    val thumbnailUrl: String? = null,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)
internal data class FastYoutubeStream(
    val title: String,
    val streamUrl: String,
    val formatId: String?,
    val isVideo: Boolean,
    val httpUserAgent: String? = null,
    val httpReferer: String? = null
)
internal data class YoutubePlaylistImportData(
    val title: String,
    val entries: List<PlaylistImportEntry>
)
private val mediaToolsInitLock = Any()
@Volatile
private var mediaToolsInitialized = false
@Volatile
private var mediaToolsInitFailureLogged = false
private const val DOWNLOAD_NOTIFICATION_PREFS = "rougo_download_notifications"
private const val PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS = "completed_download_notification_ids"
private val completedDownloadNotificationLock = Any()
internal fun ensureMediaToolsReady(context: Context): Boolean {
    if (mediaToolsInitialized) return true
    val appContext = context.applicationContext
    return synchronized(mediaToolsInitLock) {
        if (mediaToolsInitialized) {
            true
        } else {
            try {
                YoutubeDL.getInstance().init(appContext)
                FFmpeg.getInstance().init(appContext)
                mediaToolsInitialized = true
                true
            } catch (t: Throwable) {
                t.printStackTrace()
                if (!mediaToolsInitFailureLogged) {
                    CrashReporter.recordHandled(appContext, "Media tools init", t)
                    mediaToolsInitFailureLogged = true
                }
                false
            }
        }
    }
}
internal fun isYoutubeUrl(url: String): Boolean {
    val host = runCatching { Uri.parse(url).host.orEmpty().lowercase(Locale.US) }.getOrDefault("")
    return host.contains("youtube.com") || host.contains("youtu.be")
}
internal fun isYoutubePlaylistUrl(url: String): Boolean {
    if (!isYoutubeUrl(url)) return false
    val uri = runCatching { Uri.parse(url) }.getOrNull() ?: return false
    val path = uri.path.orEmpty().lowercase(Locale.US)
    val listId = uri.getQueryParameter("list")
    return !listId.isNullOrBlank() || path.startsWith("/playlist")
}
internal fun playableYoutubeUrl(url: String): String? {
    val uri = runCatching { Uri.parse(url) }.getOrNull() ?: return null
    val host = uri.host.orEmpty().lowercase(Locale.US)
    val segments = uri.pathSegments

    val hasVideoId = when {
        host == "youtu.be" || host.endsWith(".youtu.be") -> segments.firstOrNull()?.isNotBlank() == true
        host.contains("youtube.com") -> {
            !uri.getQueryParameter("v").isNullOrBlank() ||
                (segments.size >= 2 && segments[0] in setOf("shorts", "live", "embed") && segments[1].isNotBlank())
        }
        else -> false
    }

    return if (hasVideoId) url else null
}
internal fun youtubeThumbnailUrl(sourceUrl: String?): String? {
    val videoId = youtubeVideoId(sourceUrl) ?: return null
    return "https://i.ytimg.com/vi/$videoId/hqdefault.jpg"
}
private fun youtubeVideoId(sourceUrl: String?): String? {
    val uri = runCatching { Uri.parse(sourceUrl ?: "") }.getOrNull() ?: return null
    val host = uri.host.orEmpty().lowercase(Locale.US)
    val segments = uri.pathSegments
    val candidate = when {
        host == "youtu.be" || host.endsWith(".youtu.be") -> segments.firstOrNull()
        host.contains("youtube.com") -> uri.getQueryParameter("v")
            ?: if (segments.size >= 2 && segments[0] in setOf("shorts", "live", "embed")) segments[1] else null
        else -> null
    }?.trim()

    return candidate?.takeIf { Regex("[A-Za-z0-9_-]{6,}").matches(it) }
}
internal fun isBilibiliUrl(url: String): Boolean {
    val host = runCatching { Uri.parse(url).host.orEmpty().lowercase(Locale.US) }.getOrDefault("")
    return host.contains("bilibili.com") || host == "b23.tv" || host.endsWith(".b23.tv")
}
internal fun isNiconicoUrl(url: String): Boolean {
    val host = runCatching { Uri.parse(url).host.orEmpty().lowercase(Locale.US) }.getOrDefault("")
    return host.contains("nicovideo.jp") || host.contains("nico.ms")
}
internal fun streamSourceLabel(context: Context, url: String?): String {
    if (url.isNullOrBlank()) return context.getString(R.string.media_source_video)
    return when {
        isYoutubeUrl(url) -> context.getString(R.string.media_source_youtube)
        isBilibiliUrl(url) -> context.getString(R.string.media_source_bilibili)
        isNiconicoUrl(url) -> context.getString(R.string.media_source_niconico)
        else -> runCatching { Uri.parse(url).host.orEmpty().removePrefix("www.") }
            .getOrDefault("")
            .ifBlank { context.getString(R.string.media_source_stream) }
    }
}
private fun addFastYoutubeOptions(context: Context, request: YoutubeDLRequest, sourceUrl: String, skipDownload: Boolean = true): YoutubeDLRequest {
    val cacheDir = File(context.cacheDir, "yt-dlp-cache").apply { mkdirs() }
    val configured = request
        .addOption("--no-playlist")
        .addOption("--no-warnings")
        .addOption("--no-progress")
        .addOption("--force-ipv4")
        .addOption("--cache-dir", cacheDir.absolutePath)

    if (skipDownload) configured.addOption("--skip-download")

    if (isYoutubeUrl(sourceUrl)) {
        // iOS/Android clients bypass the Web JS challenge.
        // Skipping webpage, configs, and js stops yt-dlp from downloading heavy HTML/JS,
        // saving several more seconds by directly hitting the lightweight mobile API!
        configured.addOption("--extractor-args", "youtube:player_client=ios,android;player_skip=webpage,configs,js")
    }

    return configured
}
private fun addYoutubePlaylistOptions(context: Context, request: YoutubeDLRequest, sourceUrl: String): YoutubeDLRequest {
    val cacheDir = File(context.cacheDir, "yt-dlp-cache").apply { mkdirs() }
    val configured = request
        .addOption("--yes-playlist")
        .addOption("--flat-playlist")
        .addOption("--ignore-errors")
        .addOption("--no-warnings")
        .addOption("--no-progress")
        .addOption("--force-ipv4")
        .addOption("--cache-dir", cacheDir.absolutePath)

    if (isYoutubeUrl(sourceUrl)) {
        configured.addOption("--extractor-args", "youtube:player_client=ios,android;player_skip=webpage,configs,js")
    }

    return configured
}
private fun fastYoutubeFormatSelector(preferredResolution: String): String {
    return when (preferredResolution) {
        YOUTUBE_RESOLUTION_AUDIO -> "bestaudio[ext=m4a]/bestaudio/best"
        YOUTUBE_RESOLUTION_HIGHEST ->
            "best[vcodec!=none][acodec!=none][ext=mp4]/best[vcodec!=none][acodec!=none]/best"
        else -> {
            val targetHeight = preferredResolution.toIntOrNull()?.coerceAtLeast(144)
            if (targetHeight == null) {
                "best[vcodec!=none][acodec!=none][ext=mp4]/best[vcodec!=none][acodec!=none]/best"
            } else {
                "best[height<=$targetHeight][vcodec!=none][acodec!=none][ext=mp4]/" +
                    "best[height<=$targetHeight][vcodec!=none][acodec!=none]/" +
                    "best[vcodec!=none][acodec!=none]/best"
            }
        }
    }
}
private fun cleanYtdlpPrintedValue(value: String?): String? {
    return value
        ?.trim()
        ?.takeIf { it.isNotBlank() && it != "NA" && it != "null" }
}
private fun sourceDefaultTitle(context: Context, url: String): String =
    context.getString(R.string.media_source_default_title, streamSourceLabel(context, url))
private fun cleanYtdlpTitle(context: Context, value: String?, sourceUrl: String): String? {
    val cleaned = cleanYtdlpPrintedValue(value)
        ?.replace(Regex("\\s+"), " ")
        ?.takeIf { !looksLikeGeneratedFileId(it) }
    return cleaned ?: sourceDefaultTitle(context, sourceUrl)
}
private fun cleanOptionalYtdlpTitle(context: Context, value: String?, sourceUrl: String): String? {
    return cleanYtdlpTitle(context, value, sourceUrl)
        ?.takeIf { it != sourceDefaultTitle(context, sourceUrl) }
}
internal fun looksLikeGeneratedFileId(value: String): Boolean {
    return Regex("(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(?:[._ -].*)?$")
        .matches(value.trim())
}
private fun titleFromDownloadedFile(context: Context, file: File, fileId: String, sourceUrl: String): String? {
    val raw = file.nameWithoutExtension
        .removePrefix(fileId)
        .trimStart('.', '-', '_', ' ')
        .replace(Regex("\\s+"), " ")
    return cleanOptionalYtdlpTitle(context, raw, sourceUrl)
}
internal fun fetchFastYoutubeStream(context: Context, url: String, preferredResolution: String): FastYoutubeStream? {
    if (!isYoutubeUrl(url)) return null
    check(ensureMediaToolsReady(context)) { "Media tools are unavailable." }
    val request = addFastYoutubeOptions(context, YoutubeDLRequest(url), url)
    request.addOption("-f", fastYoutubeFormatSelector(preferredResolution))
    request.addOption("--print", "%(title)s|||%(format_id)s|||%(url)s|||%(vcodec)s|||%(http_headers)j")

    return try {
        val response = YoutubeDL.getInstance().execute(request, null, false)
        val outLine = response.out.lineSequence().lastOrNull { it.contains("|||") } ?: return null
        val parts = outLine.split("|||")
        if (parts.size >= 5) {
            val title = parts[0].takeIf { it.isNotBlank() && it != "NA" && it != "null" }
                ?: context.getString(R.string.media_source_youtube_stream)
            val formatId = parts[1].takeIf { it.isNotBlank() && it != "NA" && it != "null" }
            val streamUrl = parts[2].takeIf { it.isNotBlank() && it != "NA" && it != "null" } ?: return null
            val vcodec = parts[3].takeIf { it.isNotBlank() && it != "NA" && it != "null" }
            val headersJson = parts[4].takeIf { it.isNotBlank() && it != "NA" && it != "null" }
            val headers = headersJson?.let {
                runCatching { parseStreamHttpHeaders(JSONObject(it)) }.getOrNull()
            }
            FastYoutubeStream(
                title = title,
                streamUrl = streamUrl,
                formatId = formatId,
                isVideo = vcodec != "none",
                httpUserAgent = headers?.first,
                httpReferer = headers?.second
            )
        } else {
            null
        }
    } catch (t: Throwable) {
        CrashReporter.recordHandled(context, "Fast YouTube stream", t)
        null
    }
}
internal fun createFastYoutubeLibraryItem(stream: FastYoutubeStream, sourceUrl: String): LibraryItem {
    return LibraryItem(
        id = UUID.randomUUID().toString(),
        title = stream.title,
        mediaUri = stream.streamUrl,
        subtitleUri = null,
        progress = 0L,
        duration = 0L,
        isVideo = stream.isVideo,
        sourceUrl = sourceUrl,
        formatId = stream.formatId,
        httpUserAgent = stream.httpUserAgent,
        httpReferer = stream.httpReferer
    )
}
internal fun youtubeBrowserOpenableUrl(url: String): String? {
    return playableYoutubeUrl(url) ?: url.takeIf { isYoutubePlaylistUrl(it) }
}

internal class YoutubeBrowserBridge(
    private val onYoutubeUrl: (String) -> Unit
) {
    private val mainHandler = Handler(Looper.getMainLooper())

    @JavascriptInterface
    fun openVideo(url: String?) {
        openYoutubeUrl(url)
    }

    @JavascriptInterface
    fun openYoutubeUrl(url: String?) {
        val youtubeUrl = url?.takeIf { it.isNotBlank() } ?: return
        mainHandler.post { onYoutubeUrl(youtubeUrl) }
    }
}
internal fun youtubeBrowserInterceptScript(): String {
    return """
        (function() {
            if (window.__rougoYoutubeBridgeInstalled) return;
            window.__rougoYoutubeBridgeInstalled = true;

            function isRougoYoutubeUrl(rawUrl) {
                try {
                    var url = new URL(rawUrl, window.location.href);
                    var host = url.hostname.toLowerCase();
                    var path = url.pathname || "";
                    return ((host === "youtu.be" || host.endsWith(".youtu.be")) && path.length > 1) ||
                        (host.indexOf("youtube.com") !== -1 &&
                            (url.searchParams.get("v") || url.searchParams.get("list") || /^\/(shorts|live|embed|playlist)\//.test(path)));
                } catch (e) {
                    return false;
                }
            }

            function openInRougo(rawUrl) {
                if (!isRougoYoutubeUrl(rawUrl) || !window.RougoYoutube) return false;
                window.RougoYoutube.openYoutubeUrl(new URL(rawUrl, window.location.href).href);
                return true;
            }

            document.addEventListener("click", function(event) {
                var node = event.target;
                while (node && node.tagName !== "A") node = node.parentElement;
                if (node && node.href && openInRougo(node.href)) {
                    event.preventDefault();
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                }
            }, true);

            var pushState = history.pushState;
            history.pushState = function() {
                var result = pushState.apply(this, arguments);
                setTimeout(function() { openInRougo(window.location.href); }, 0);
                return result;
            };

            var replaceState = history.replaceState;
            history.replaceState = function() {
                var result = replaceState.apply(this, arguments);
                setTimeout(function() { openInRougo(window.location.href); }, 0);
                return result;
            };

            window.addEventListener("popstate", function() {
                setTimeout(function() { openInRougo(window.location.href); }, 0);
            });

            openInRougo(window.location.href);
        })();
    """.trimIndent()
}
internal fun stopYoutubeWebViewPlayback(webView: WebView?) {
    webView?.stopLoading()
    webView?.evaluateJavascript(
        """
            (function() {
                document.querySelectorAll("video, audio").forEach(function(media) {
                    try {
                        media.pause();
                        media.removeAttribute("src");
                        media.load();
                    } catch (e) {}
                });
            })();
        """.trimIndent(),
        null
    )
}
internal fun fetchYoutubeSetupData(context: Context, url: String): YoutubeSetupData {
    val json = fetchYoutubeInfoJson(context, url)
    val headers = parseStreamHttpHeaders(json)
    val isYoutubeSource = isYoutubeUrl(url)
    val title = cleanYtdlpTitle(
        context,
        firstCleanMetadataValue(
            json.optString("fulltitle"),
            json.optString("title"),
            json.optString("alt_title")
        ),
        url
    ) ?: sourceDefaultTitle(context, url)

    return YoutubeSetupData(
        title = title,
        fallbackUrl = json.optString("url").takeIf { it.isNotBlank() },
        formats = parseYoutubeFormats(json),
        subtitleChoices = if (isYoutubeSource) parseYoutubeSubtitleChoices(json) else emptyList(),
        thumbnailUrl = bestThumbnailUrl(json),
        httpUserAgent = headers.first,
        httpReferer = headers.second
    )
}
internal fun fetchYoutubePlaylistImportData(context: Context, url: String): YoutubePlaylistImportData? {
    if (!isYoutubePlaylistUrl(url)) return null
    check(ensureMediaToolsReady(context)) { "Media tools are unavailable." }

    val request = addYoutubePlaylistOptions(context, YoutubeDLRequest(url), url)
    request.addOption("--dump-single-json")

    val response = YoutubeDL.getInstance().execute(request, null, false)
    return parseYoutubePlaylistImportData(JSONObject(extractDumpedJson(response.out)))
        .takeIf { it.entries.isNotEmpty() }
}
internal fun parseYoutubePlaylistImportData(json: JSONObject): YoutubePlaylistImportData {
    val title = firstCleanMetadataValue(
        cleanYtdlpPrintedValue(json.optString("title")),
        cleanYtdlpPrintedValue(json.optString("playlist_title"))
    ) ?: "Playlist"
    val entriesJson = json.optJSONArray("entries") ?: JSONArray()
    val entries = mutableListOf<PlaylistImportEntry>()

    for (index in 0 until entriesJson.length()) {
        val entry = entriesJson.optJSONObject(index) ?: continue
        val entryUrl = youtubePlaylistEntrySourceUrl(entry) ?: continue
        val entryTitle = firstCleanMetadataValue(
            cleanYtdlpPrintedValue(entry.optString("title")),
            cleanYtdlpPrintedValue(entry.optString("fulltitle"))
        ) ?: "Video ${entries.size + 1}"
        entries += PlaylistImportEntry(
            title = entryTitle,
            sourceUrl = entryUrl,
            thumbnailUrl = bestThumbnailUrl(entry),
            isVideo = true
        )
    }

    return YoutubePlaylistImportData(title, entries.distinctBy { it.sourceUrl })
}
private fun youtubePlaylistEntrySourceUrl(entry: JSONObject): String? {
    val webpageUrl = cleanYtdlpPrintedValue(entry.optString("webpage_url"))
    if (webpageUrl?.startsWith("http", ignoreCase = true) == true) return webpageUrl

    val rawUrl = cleanYtdlpPrintedValue(entry.optString("url"))
    if (rawUrl?.startsWith("http", ignoreCase = true) == true) return rawUrl

    val id = cleanYtdlpPrintedValue(entry.optString("id"))
        ?: rawUrl?.takeIf { Regex("[A-Za-z0-9_-]{6,}").matches(it) }
        ?: return null

    return "https://www.youtube.com/watch?v=$id"
}
private fun parseStreamHttpHeaders(json: JSONObject): Pair<String?, String?> {
    val headers = json.optJSONObject("http_headers")
    val userAgent = headers?.optCleanString("User-Agent")
        ?: headers?.optCleanString("user-agent")
        ?: json.optCleanString("user_agent")
    val referer = headers?.optCleanString("Referer")
        ?: headers?.optCleanString("referer")
        ?: headers?.optCleanString("Referrer")
    return userAgent to referer
}
internal suspend fun createYoutubeLibraryItem(
    context: Context,
    setupData: YoutubeSetupData?,
    format: YoutubeStreamFormat,
    subtitleUri: String?,
    sourceUrl: String
): LibraryItem = withContext(Dispatchers.IO) {
    val itemId = UUID.randomUUID().toString()
    val coverArtPath = setupData?.thumbnailUrl?.let { downloadRemoteCover(context, itemId, it) }
    LibraryItem(
        id = itemId,
        title = setupData?.title ?: context.getString(R.string.media_source_youtube_stream),
        mediaUri = sourceUrl,
        subtitleUri = subtitleUri,
        progress = 0L,
        duration = 0L,
        isVideo = format.vcodec != "none",
        sourceUrl = sourceUrl,
        formatId = format.formatId,
        coverArtPath = coverArtPath,
        httpUserAgent = setupData?.httpUserAgent,
        httpReferer = setupData?.httpReferer
    )
}
private fun bestThumbnailUrl(json: JSONObject): String? {
    val thumbnails = json.optJSONArray("thumbnails")
    if (thumbnails != null && thumbnails.length() > 0) {
        var bestUrl: String? = null
        var bestArea = -1
        for (i in 0 until thumbnails.length()) {
            val item = thumbnails.optJSONObject(i) ?: continue
            val url = item.optString("url").takeIf { it.isNotBlank() } ?: continue
            val area = item.optInt("width", 0) * item.optInt("height", 0)
            if (area >= bestArea) {
                bestUrl = url
                bestArea = area
            }
        }
        if (!bestUrl.isNullOrBlank()) return bestUrl
    }
    return json.optString("thumbnail").takeIf { it.isNotBlank() }
}
internal fun downloadRemoteCover(context: Context, itemId: String, url: String): String? {
    return try {
        val connection = URL(url).openConnection() as HttpURLConnection
        connection.connectTimeout = 10000
        connection.readTimeout = 15000
        connection.setRequestProperty("User-Agent", "Mozilla/5.0")
        if (connection.responseCode !in 200..299) return null
        val bytes = connection.inputStream.use { it.readBytes() }
        if (bytes.isEmpty() || bytes.size > 8 * 1024 * 1024) return null
        cacheCoverBytes(context, itemId, bytes)
    } catch (e: Exception) {
        null
    }
}
internal fun youtubeResolutionLabel(context: Context, key: String): String {
    val labelRes = YOUTUBE_RESOLUTION_OPTIONS.firstOrNull { it.key == key }?.labelRes
        ?: R.string.option_youtube_quality_ask
    return context.getString(labelRes)
}
private fun hasPostNotificationsPermission(context: Context): Boolean {
    return Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
        ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED
}
internal fun hasPlayerNotificationPermission(context: Context): Boolean = hasPostNotificationsPermission(context)
private fun createPlayerNotificationChannel(context: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return

    val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (manager.getNotificationChannel(PLAYER_NOTIFICATION_CHANNEL_ID) != null) return

    val channel = NotificationChannel(
        PLAYER_NOTIFICATION_CHANNEL_ID,
        context.getString(R.string.notification_channel_player_name),
        NotificationManager.IMPORTANCE_LOW
    ).apply {
        description = context.getString(R.string.notification_channel_player_description)
        setShowBadge(false)
    }
    manager.createNotificationChannel(channel)
}
private fun createDownloadNotificationChannel(context: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return

    val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (manager.getNotificationChannel(DOWNLOAD_NOTIFICATION_CHANNEL_ID) != null) return

    val channel = NotificationChannel(
        DOWNLOAD_NOTIFICATION_CHANNEL_ID,
        context.getString(R.string.notification_channel_downloads_name),
        NotificationManager.IMPORTANCE_LOW
    ).apply {
        description = context.getString(R.string.notification_channel_downloads_description)
        setShowBadge(false)
    }
    manager.createNotificationChannel(channel)
}
private fun playerNotificationPendingIntent(context: Context, action: String): PendingIntent {
    val flags = PendingIntent.FLAG_UPDATE_CURRENT or
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) PendingIntent.FLAG_IMMUTABLE else 0
    val intent = Intent(action).setPackage(context.packageName)
    return PendingIntent.getBroadcast(context, action.hashCode(), intent, flags)
}
private fun appContentPendingIntent(context: Context, requestCode: Int = 0): PendingIntent {
    val flags = PendingIntent.FLAG_UPDATE_CURRENT or
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) PendingIntent.FLAG_IMMUTABLE else 0
    return PendingIntent.getActivity(
        context,
        requestCode,
        Intent(context, MainActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP),
        flags
    )
}
private fun nativeNotificationBuilder(context: Context, channelId: String): Notification.Builder {
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(context, channelId)
    } else {
        @Suppress("DEPRECATION")
        Notification.Builder(context)
    }
}
private fun nativeNotificationAction(icon: Int, title: String, pendingIntent: PendingIntent): Notification.Action {
    return Notification.Action.Builder(icon, title, pendingIntent).build()
}
internal fun showPlayerNotification(
    context: Context,
    title: String,
    subtitle: String?,
    coverArtPath: String?,
    currentPos: Long,
    duration: Long,
    isPlaying: Boolean,
    skipSeconds: Int,
    mediaSessionToken: MediaSession.Token?
) {
    if (!hasPostNotificationsPermission(context)) return
    createPlayerNotificationChannel(context)

    val timeText = "${formatTime(currentPos)} / ${formatTime(duration)}"
    val largeIcon = coverArtPath?.let { decodeSampledBitmapFile(it, maxSize = 512) }
    val actions = listOf(
        nativeNotificationAction(
            android.R.drawable.ic_media_rew,
            context.getString(R.string.notification_action_rewind, skipSeconds),
            playerNotificationPendingIntent(context, ACTION_PLAYER_REWIND)
        ),
        nativeNotificationAction(
            if (isPlaying) android.R.drawable.ic_media_pause else android.R.drawable.ic_media_play,
            context.getString(if (isPlaying) R.string.common_pause else R.string.common_play),
            playerNotificationPendingIntent(context, ACTION_PLAYER_PLAY_PAUSE)
        ),
        nativeNotificationAction(
            android.R.drawable.ic_media_ff,
            context.getString(R.string.notification_action_forward, skipSeconds),
            playerNotificationPendingIntent(context, ACTION_PLAYER_FORWARD)
        ),
        nativeNotificationAction(
            android.R.drawable.ic_menu_close_clear_cancel,
            context.getString(R.string.common_stop),
            playerNotificationPendingIntent(context, ACTION_PLAYER_STOP)
        )
    )

    val notification = nativeNotificationBuilder(context, PLAYER_NOTIFICATION_CHANNEL_ID)
        .setSmallIcon(if (isPlaying) android.R.drawable.ic_media_play else android.R.drawable.ic_media_pause)
        .setContentTitle(title)
        .setContentText(subtitle ?: timeText)
        .setSubText(timeText)
        .setContentIntent(appContentPendingIntent(context))
        .setDeleteIntent(playerNotificationPendingIntent(context, ACTION_PLAYER_STOP))
        .setVisibility(Notification.VISIBILITY_PUBLIC)
        .setOnlyAlertOnce(true)
        .setShowWhen(false)
        .setOngoing(isPlaying)
        .setCategory(Notification.CATEGORY_TRANSPORT)
        .setPriority(Notification.PRIORITY_LOW)
        .apply {
            if (largeIcon != null) setLargeIcon(largeIcon)
            actions.forEach { addAction(it) }
            setStyle(
                Notification.MediaStyle()
                    .setMediaSession(mediaSessionToken)
                    .setShowActionsInCompactView(0, 1, 2)
            )
        }
        .build()

    try {
        NotificationManagerCompat.from(context).notify(PLAYER_NOTIFICATION_ID, notification)
    } catch (e: SecurityException) {
        e.printStackTrace()
    }
}
internal fun cancelPlayerNotification(context: Context) {
    try {
        NotificationManagerCompat.from(context).cancel(PLAYER_NOTIFICATION_ID)
    } catch (e: Exception) {
        e.printStackTrace()
    }
}
private fun downloadNotificationId(key: String): Int {
    return DOWNLOAD_NOTIFICATION_ID_BASE + ((key.hashCode() and 0x7fffffff) % 1000)
}
private fun completedDownloadPrefs(context: Context) =
    context.applicationContext.getSharedPreferences(DOWNLOAD_NOTIFICATION_PREFS, Context.MODE_PRIVATE)

private fun rememberCompletedDownloadNotification(context: Context, notificationId: Int) {
    synchronized(completedDownloadNotificationLock) {
        val prefs = completedDownloadPrefs(context)
        val current = prefs.getStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, emptySet()).orEmpty()
        prefs.edit {
            putStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, current + notificationId.toString())
        }
    }
}

private fun forgetCompletedDownloadNotification(context: Context, notificationId: Int) {
    synchronized(completedDownloadNotificationLock) {
        val prefs = completedDownloadPrefs(context)
        val current = prefs.getStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, emptySet()).orEmpty()
        if (current.isNotEmpty()) {
            prefs.edit {
                putStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, current - notificationId.toString())
            }
        }
    }
}

internal fun clearCompletedDownloadNotifications(context: Context) {
    val ids = synchronized(completedDownloadNotificationLock) {
        val prefs = completedDownloadPrefs(context)
        val current = prefs.getStringSet(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS, emptySet()).orEmpty()
        prefs.edit { remove(PREF_COMPLETED_DOWNLOAD_NOTIFICATION_IDS) }
        current.mapNotNull { it.toIntOrNull() }
    }
    ids.forEach { notificationId ->
        try {
            NotificationManagerCompat.from(context).cancel(notificationId)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}

private fun cancelDownloadNotification(context: Context, key: String) {
    val notificationId = downloadNotificationId(key)
    forgetCompletedDownloadNotification(context, notificationId)
    try {
        NotificationManagerCompat.from(context).cancel(notificationId)
    } catch (e: Exception) {
        e.printStackTrace()
    }
}

private fun showDownloadNotification(context: Context, key: String, notification: NotificationCompat.Builder.() -> Unit): Boolean {
    if (!hasPostNotificationsPermission(context)) return false
    createDownloadNotificationChannel(context)

    val builder = NotificationCompat.Builder(context, DOWNLOAD_NOTIFICATION_CHANNEL_ID)
        .setSmallIcon(android.R.drawable.stat_sys_download)
        .setContentIntent(appContentPendingIntent(context, downloadNotificationId(key)))
        .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
        .setOnlyAlertOnce(true)
        .setShowWhen(true)
        .setLocalOnly(false)
        .apply(notification)

    try {
        NotificationManagerCompat.from(context).notify(downloadNotificationId(key), builder.build())
        return true
    } catch (e: SecurityException) {
        e.printStackTrace()
        return false
    }
}
private fun showDownloadProgressNotification(
    context: Context,
    key: String,
    title: String,
    progressPercent: Int?,
    detail: String = context.getString(R.string.download_progress_downloading)
) {
    forgetCompletedDownloadNotification(context, downloadNotificationId(key))
    showDownloadNotification(context, key) {
        setSmallIcon(android.R.drawable.stat_sys_download)
        setContentTitle(title)
        setContentText(detail)
        setOngoing(true)
        setAutoCancel(false)
        setCategory(NotificationCompat.CATEGORY_PROGRESS)
        setPriority(NotificationCompat.PRIORITY_LOW)
        if (progressPercent != null) {
            setProgress(100, progressPercent.coerceIn(0, 100), false)
        } else {
            setProgress(0, 0, true)
        }
    }
}
private fun showDownloadCompleteNotification(context: Context, key: String, title: String) {
    if (RougoForegroundTracker.isForeground) {
        cancelDownloadNotification(context, key)
        return
    }

    val posted = showDownloadNotification(context, key) {
        setSmallIcon(android.R.drawable.stat_sys_download_done)
        setContentTitle(context.getString(R.string.download_complete_title))
        setContentText(title)
        setOngoing(false)
        setAutoCancel(true)
        setCategory(NotificationCompat.CATEGORY_STATUS)
        setPriority(NotificationCompat.PRIORITY_DEFAULT)
        setProgress(0, 0, false)
    }
    if (posted) rememberCompletedDownloadNotification(context, downloadNotificationId(key))
}
private fun showDownloadFailedNotification(context: Context, key: String, title: String, cancelled: Boolean = false) {
    forgetCompletedDownloadNotification(context, downloadNotificationId(key))
    showDownloadNotification(context, key) {
        setSmallIcon(android.R.drawable.stat_notify_error)
        setContentTitle(context.getString(if (cancelled) R.string.download_cancelled_title else R.string.download_failed_title))
        setContentText(title)
        setOngoing(false)
        setAutoCancel(true)
        setCategory(NotificationCompat.CATEGORY_ERROR)
        setPriority(NotificationCompat.PRIORITY_DEFAULT)
        setProgress(0, 0, false)
    }
}
private fun downloadProgressPercent(progress: Float): Int? {
    if (progress.isNaN() || progress.isInfinite() || progress < 0f || progress > 100f) return null
    return progress.roundToInt().coerceIn(0, 100)
}
private fun downloadProgressDetail(context: Context, progressPercent: Int?, etaSeconds: Long, line: String): String {
    if (progressPercent == null) {
        return line.takeIf { it.isNotBlank() }?.take(80) ?: context.getString(R.string.download_progress_downloading)
    }
    val etaText = when {
        etaSeconds <= 0L -> null
        etaSeconds < 60L -> context.getString(R.string.download_eta_seconds, etaSeconds)
        etaSeconds < 3600L -> context.getString(R.string.download_eta_minutes, etaSeconds / 60L)
        else -> context.getString(R.string.download_eta_hours_minutes, etaSeconds / 3600L, (etaSeconds % 3600L) / 60L)
    }
    return if (etaText != null) {
        context.getString(R.string.download_progress_detail, progressPercent, etaText)
    } else {
        context.getString(R.string.download_progress_percent_only, progressPercent)
    }
}
internal fun selectPreferredYoutubeSubtitle(choices: List<YoutubeSubtitleChoice>, preferredLanguage: String): YoutubeSubtitleChoice? {
    if (choices.isEmpty()) return null
    if (preferredLanguage == "any") return choices.firstOrNull()

    val normalized = preferredLanguage.lowercase(Locale.US)
    return choices.firstOrNull { choice ->
        val code = choice.languageCode.lowercase(Locale.US)
        code == normalized || code.startsWith("$normalized-")
    } ?: choices.firstOrNull()
}
private fun youtubeSubtitleChoiceKey(choice: YoutubeSubtitleChoice): String {
    return "${choice.languageCode}:${choice.isAutoGenerated}"
}
private fun preferredYoutubeSubtitleCandidates(
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): List<YoutubeSubtitleChoice> {
    val preferredChoice = selectPreferredYoutubeSubtitle(choices, preferredLanguage) ?: return emptyList()
    val normalizedPreference = preferredLanguage.lowercase(Locale.US)
    val preferredLanguageMatches = if (normalizedPreference == "any") {
        emptyList()
    } else {
        choices.filter { choice ->
            val code = choice.languageCode.lowercase(Locale.US)
            code == normalizedPreference || code.startsWith("$normalizedPreference-")
        }
    }
    return (listOf(preferredChoice) +
        choices.filter { it.languageCode == preferredChoice.languageCode } +
        preferredLanguageMatches +
        choices.take(2))
        .distinctBy { youtubeSubtitleChoiceKey(it) }
}
internal fun downloadPreferredYoutubeSubtitle(
    context: Context,
    url: String,
    choices: List<YoutubeSubtitleChoice>,
    preferredLanguage: String
): String? {
    preferredYoutubeSubtitleCandidates(choices, preferredLanguage).forEach { choice ->
        val subtitleUri = downloadYoutubeSubtitle(context, url, choice.languageCode, choice.isAutoGenerated)
        if (subtitleUri != null) return subtitleUri
    }
    return null
}
internal fun selectPreferredYoutubeFormat(
    formats: List<YoutubeStreamFormat>,
    preferredResolution: String
): YoutubeStreamFormat? {
    val playable = formats.filter { !it.url.isNullOrBlank() || !it.manifestUrl.isNullOrBlank() }
    val audioFormats = playable
        .filter { it.vcodec == "none" && it.acodec != "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { if (it.isVlcFriendlyAudioFormat()) 1 else 0 }.thenByDescending { it.tbr }.thenByDescending { it.formatId ?: "" })
    val videoFormats = playable
        .filter { it.vcodec != "none" && it.acodec != "none" }
        .sortedWith(compareByDescending<YoutubeStreamFormat> { it.height }.thenByDescending { if (it.isVlcFriendlyVideoFormat()) 1 else 0 }.thenByDescending { it.tbr })

    return when (preferredResolution) {
        YOUTUBE_RESOLUTION_AUDIO -> audioFormats.firstOrNull() ?: videoFormats.firstOrNull()
        YOUTUBE_RESOLUTION_HIGHEST -> videoFormats.firstOrNull() ?: audioFormats.firstOrNull()
        else -> {
            val targetHeight = preferredResolution.toIntOrNull()
            if (targetHeight == null) {
                videoFormats.firstOrNull() ?: audioFormats.firstOrNull()
            } else {
                videoFormats.firstOrNull { it.height in 1..targetHeight }
                    ?: videoFormats.lastOrNull()
                    ?: audioFormats.firstOrNull()
            }
        }
    }
}
internal fun resolveYoutubeStreamUrl(context: Context, url: String, formatId: String?): String? {
    StreamUrlCache.get(context, url, formatId)?.let { return it }
    if (!ensureMediaToolsReady(context)) return null
    val request = addFastYoutubeOptions(context, YoutubeDLRequest(url), url)
    if (formatId != null) {
        request.addOption("-f", formatId)
    } else {
        request.addOption("-f", "best[vcodec!=none][acodec!=none][ext=mp4]/best[vcodec!=none][acodec!=none]/best")
    }
    request.addOption("--print", "url")
    return try {
        val response = YoutubeDL.getInstance().execute(request, null, false)
        response.out.lineSequence()
            .firstOrNull { it.trim().startsWith("http") }
            ?.trim()
            ?.also { resolvedUrl ->
                StreamUrlCache.put(context, url, formatId, resolvedUrl, detectStreamProvider(url))
            }
    } catch (e: Exception) {
        e.printStackTrace()
        null
    }
}

internal fun invalidateResolvedStreamUrl(context: Context, url: String, formatId: String?) {
    StreamUrlCache.invalidate(context, url, formatId)
}
private fun fetchYoutubeInfoJson(context: Context, url: String): JSONObject {
    check(ensureMediaToolsReady(context)) { "Media tools are unavailable." }
    val request = addFastYoutubeOptions(context, YoutubeDLRequest(url), url)
    request.addOption("--dump-json")

    val response = YoutubeDL.getInstance().execute(request, null, false)
    return JSONObject(extractDumpedJson(response.out))
}
internal fun downloadYoutubeSubtitle(context: Context, url: String, languageCode: String, isAutoGenerated: Boolean): String? {
    if (!isYoutubeUrl(url)) return null
    if (!ensureMediaToolsReady(context)) return null
    val destDir = File(context.getExternalFilesDir(Environment.DIRECTORY_MOVIES), "RougoSubs")
    destDir.mkdirs()

    val fileId = UUID.randomUUID().toString()
    val request = addFastYoutubeOptions(context, YoutubeDLRequest(url), url)
    request.addOption(if (isAutoGenerated) "--write-auto-subs" else "--write-subs")
    request.addOption("--sub-langs", languageCode)
    request.addOption("--sub-format", "vtt/srt/best")
    request.addOption("--convert-subs", "srt")
    request.addOption("-o", "${destDir.absolutePath}/$fileId.%(ext)s")

    return try {
        YoutubeDL.getInstance().execute(request, fileId, false)
        val subtitleUri = findDownloadedSubtitle(destDir, fileId)?.let { Uri.fromFile(it).toString() }
        if (subtitleUri == null && !isAutoGenerated) {
            downloadYoutubeSubtitle(context, url, languageCode, true)
        } else {
            subtitleUri
        }
    } catch (e: Exception) {
        e.printStackTrace()
        if (!isAutoGenerated) {
            downloadYoutubeSubtitle(context, url, languageCode, true)
        } else {
            null
        }
    }
}
internal fun downloadVideoLinkToLibraryItem(context: Context, url: String, existingItem: LibraryItem? = null): LibraryItem? {
    val itemId = existingItem?.id ?: UUID.randomUUID().toString()
    val fileId = itemId.replace(Regex("[^A-Za-z0-9_-]"), "_")
    val notificationKey = "media_download_$fileId"
    val initialTitle = existingItem?.title?.takeIf { !looksLikeGeneratedFileId(it) }
        ?: sourceDefaultTitle(context, url)

    showDownloadProgressNotification(context, notificationKey, initialTitle, null, context.getString(R.string.download_progress_preparing))

    if (!ensureMediaToolsReady(context)) {
        showDownloadFailedNotification(context, notificationKey, initialTitle)
        return null
    }

    val setupData = runCatching { fetchYoutubeSetupData(context, url) }.getOrNull()
    val notificationTitle = cleanOptionalYtdlpTitle(context, setupData?.title, url)
        ?: initialTitle
    val destDir = File(context.getExternalFilesDir(Environment.DIRECTORY_MOVIES), "RougoDownloads").apply { mkdirs() }

    val request = addFastYoutubeOptions(context, YoutubeDLRequest(url), url, skipDownload = false)
    request.addOption("-f", "bestvideo[height<=720]+bestaudio/best[height<=720]/best")
    request.addOption("--merge-output-format", "mp4")
    request.addOption("-o", "${destDir.absolutePath}/$fileId.%(title)s.%(ext)s")

    return try {
        var lastProgressNotificationAt = 0L
        var lastProgressPercent = -1
        showDownloadProgressNotification(context, notificationKey, notificationTitle, null, context.getString(R.string.download_progress_starting))

        YoutubeDL.getInstance().execute(request, fileId, false) { progress, etaSeconds, line ->
            val progressPercent = downloadProgressPercent(progress)
            val now = SystemClock.elapsedRealtime()
            val progressChanged = progressPercent != null && progressPercent != lastProgressPercent
            if (progressChanged || now - lastProgressNotificationAt >= 1000L) {
                lastProgressNotificationAt = now
                if (progressPercent != null) lastProgressPercent = progressPercent
                showDownloadProgressNotification(
                    context = context,
                    key = notificationKey,
                    title = notificationTitle,
                    progressPercent = progressPercent,
                    detail = downloadProgressDetail(context, progressPercent, etaSeconds, line)
                )
            }
        }

        showDownloadProgressNotification(context, notificationKey, notificationTitle, 100, context.getString(R.string.download_progress_finalizing))
        val downloadedFile = destDir.listFiles()
            ?.filter { it.isFile && it.name.startsWith(fileId) && it.length() > 0L && !it.name.endsWith(".part") }
            ?.maxByOrNull { it.lastModified() }
        if (downloadedFile == null) {
            showDownloadFailedNotification(context, notificationKey, notificationTitle)
            return null
        }

        val mediaUri = Uri.fromFile(downloadedFile)
        val metadata = extractMediaMetadata(context, mediaUri, itemId, isVideo = true)
        val fallbackTitle = cleanOptionalYtdlpTitle(context, setupData?.title, url)
            ?: existingItem?.title?.takeIf { !looksLikeGeneratedFileId(it) }
            ?: titleFromDownloadedFile(context, downloadedFile, fileId, url)
            ?: sourceDefaultTitle(context, url)
        val baseItem = LibraryItem(
            id = itemId,
            title = fallbackTitle,
            mediaUri = mediaUri.toString(),
            subtitleUri = existingItem?.subtitleUri,
            progress = existingItem?.progress ?: 0L,
            duration = metadata.durationMs ?: 0L,
            isVideo = true,
            sourceUrl = existingItem?.sourceUrl ?: url,
            formatId = existingItem?.formatId,
            recordings = existingItem?.recordings ?: emptyList(),
            coverArtPath = metadata.coverArtPath
                ?: setupData?.thumbnailUrl?.let { downloadRemoteCover(context, itemId, it) }
                ?: existingItem?.coverArtPath,
            httpUserAgent = existingItem?.httpUserAgent ?: setupData?.httpUserAgent,
            httpReferer = existingItem?.httpReferer ?: setupData?.httpReferer,
            itemKind = existingItem?.itemKind ?: LibraryItemKind.Media,
            parentId = existingItem?.parentId,
            playlistSourceUrl = existingItem?.playlistSourceUrl,
            playlistItemIndex = existingItem?.playlistItemIndex ?: 0
        )
        val mergedItem = mergeMetadataIntoItem(baseItem, metadata, fallbackTitle)
        showDownloadCompleteNotification(context, notificationKey, mergedItem.title)
        mergedItem
    } catch (t: Throwable) {
        t.printStackTrace()
        CrashReporter.recordHandled(context, "Download video link", t)
        showDownloadFailedNotification(
            context,
            notificationKey,
            notificationTitle,
            cancelled = t is InterruptedException || t::class.java.simpleName.contains("Canceled", ignoreCase = true)
        )
        null
    }
}
private fun findDownloadedSubtitle(destDir: File, fileId: String): File? {
    return destDir.listFiles()
        ?.filter {
            val ext = it.extension.lowercase(Locale.US)
            it.name.startsWith(fileId) && it.length() > 0L && (ext == "srt" || ext == "vtt" || ext == "ass")
        }
        ?.maxWithOrNull(compareBy<File> {
            when (it.extension.lowercase(Locale.US)) {
                "srt" -> 3
                "vtt" -> 2
                else -> 1
            }
        }.thenBy { it.lastModified() })
}
private fun extractDumpedJson(output: String): String {
    val trimmed = output.trim()
    if (trimmed.startsWith("{")) return trimmed

    return output.lineSequence()
        .map { it.trim() }
        .firstOrNull { it.startsWith("{") && it.endsWith("}") }
        ?: trimmed
}
private fun parseYoutubeSubtitleChoices(json: JSONObject): List<YoutubeSubtitleChoice> {
    val choices = linkedMapOf<String, YoutubeSubtitleChoice>()

    fun addChoices(groupName: String, isAutoGenerated: Boolean) {
        val group = json.optJSONObject(groupName) ?: return
        val keys = group.keys()
        while (keys.hasNext()) {
            val languageCode = keys.next()
            if (languageCode == "live_chat") continue
            val tracks = group.optJSONArray(languageCode)
            if (tracks == null || tracks.length() == 0) continue

            val firstTrack = tracks.optJSONObject(0)
            val trackName = firstTrack?.optString("name").orEmpty().takeIf { it.isNotBlank() }
            val localeName = Locale.forLanguageTag(languageCode).displayName.takeIf { it.isNotBlank() && it != languageCode }
            val languageName = trackName ?: localeName ?: languageCode
            val label = if (isAutoGenerated) {
                "$languageName ($languageCode, Auto)"
            } else {
                "$languageName ($languageCode)"
            }
            choices["$languageCode:$isAutoGenerated"] = YoutubeSubtitleChoice(label, languageCode, isAutoGenerated)
        }
    }

    addChoices("subtitles", false)
    addChoices("automatic_captions", true)

    fun languagePriority(choice: YoutubeSubtitleChoice): Int {
        val code = choice.languageCode.lowercase(Locale.US)
        return when {
            code == "ja" || code.startsWith("ja-") -> 0
            code == "en" || code.startsWith("en-") -> 1
            else -> 2
        }
    }

    return choices.values.sortedWith(
        compareBy<YoutubeSubtitleChoice> { languagePriority(it) }
            .thenBy { it.isAutoGenerated }
            .thenBy { it.label.lowercase(Locale.US) }
    )
}
private fun parseYoutubeFormats(json: JSONObject): List<YoutubeStreamFormat> {
    val formatsJson = json.optJSONArray("formats") ?: return emptyList()
    val formats = mutableListOf<YoutubeStreamFormat>()

    for (i in 0 until formatsJson.length()) {
        val format = formatsJson.optJSONObject(i) ?: continue
        formats.add(
            YoutubeStreamFormat(
                formatId = format.optString("format_id").takeIf { it.isNotBlank() },
                formatNote = format.optString("format_note").takeIf { it.isNotBlank() },
                ext = format.optString("ext").takeIf { it.isNotBlank() },
                vcodec = format.optString("vcodec").takeIf { it.isNotBlank() },
                acodec = format.optString("acodec").takeIf { it.isNotBlank() },
                height = format.optInt("height", 0),
                tbr = format.optDouble("tbr", 0.0).toInt(),
                url = format.optString("url").takeIf { it.isNotBlank() },
                manifestUrl = format.optString("manifest_url").takeIf { it.isNotBlank() },
                protocol = format.optString("protocol").takeIf { it.isNotBlank() }
            )
        )
    }

    return formats
}
internal fun initialPlayableMediaUri(item: LibraryItem): String? {
    val mediaUri = item.mediaUri.trim()
    if (mediaUri.isBlank()) return null
    if (item.sourceUrl == null) return mediaUri
    if (item.hasDownloadedLocalCopy()) return mediaUri
    if (mediaUri != item.sourceUrl.trim()) return mediaUri
    return null
}
private fun YoutubeStreamFormat.bestPlaybackUrl(): String? {
    val manifest = manifestUrl?.takeIf { it.isNotBlank() }
    val directUrl = url?.takeIf { it.isNotBlank() }
    val protocolValue = protocol?.lowercase(Locale.US).orEmpty()
    return when {
        protocolValue.contains("m3u8") -> directUrl ?: manifest
        protocolValue.contains("dash") -> manifest ?: directUrl
        isVlcFriendlyVideoFormat() || isVlcFriendlyAudioFormat() -> directUrl ?: manifest
        else -> manifest ?: directUrl
    }
}
internal fun YoutubeStreamFormat.isVlcFriendlyVideoFormat(): Boolean {
    if (vcodec == "none" || acodec == "none") return false
    val extValue = ext?.lowercase(Locale.US).orEmpty()
    val videoCodec = vcodec?.lowercase(Locale.US).orEmpty()
    val audioCodec = acodec?.lowercase(Locale.US).orEmpty()
    return extValue == "mp4" &&
        (videoCodec.startsWith("avc") || videoCodec.startsWith("h264")) &&
        (audioCodec.startsWith("mp4a") || audioCodec.startsWith("aac"))
}
internal fun YoutubeStreamFormat.isVlcFriendlyAudioFormat(): Boolean {
    if (vcodec != "none" || acodec == "none") return false
    val extValue = ext?.lowercase(Locale.US).orEmpty()
    val audioCodec = acodec?.lowercase(Locale.US).orEmpty()
    return extValue == "m4a" || extValue == "mp4" || audioCodec.startsWith("mp4a") || audioCodec.startsWith("aac")
}
